spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/delivery
    username: root
    password: Bont
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
    driver-class-name: org.mariadb.jdbc.Driver

# Configure Jackson to handle Hibernate objects
jackson:
  serialization:
    FAIL_ON_EMPTY_BEANS: false
  mapper:
    DEFAULT_VIEW_INCLUSION: true
    serialization:
      INDENT_OUTPUT: true
  deserialization:
    UNWRAP_ROOT_VALUE: false